### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by astrojuanlu**
- Use new domain for links
- Add link to 2021 edition

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Just got an email saying:

> The page build completed successfully, but returned the following warning for the `master` branch:
> The custom domain `www.scipy.lat` is already taken. Check out https://docs.github.com/articles/troubleshooting-custom-domains#cname-errors for more information.

I think the repository might have the wrong configuration? It looked weird to me that `gh-pages` contained the sources.

**Comment by astrojuanlu** [comment]
(Ignore my previous comment, I know what happened)

**Review by arthuralvim — APPROVED** [review]
The changes look fine but I wasn't able to build the project and check if the generated pages are correct.

A suggestion for the next PR is to change the base structure of this project to match some modern stack such as Hugo + Bootstrap or a python one with Lektor + Bootstrap. We could use Github Actions as CI.

**Comment by astrojuanlu** [comment]
I _think_ the deployment instructions are these? https://github.com/scipy-latinamerica/scipy-latinamerica.github.io/tree/gh-pages#how-to-build-it

About changing the backend, I don't oppose it, but it can be a bit of work, even if we don't strive to keep the same visual appearance. I will leave it to a brave soul :)

**Pull request merged**
